#!/usr/bin/env nu

# Draft a production release following the CalVer scheme documented in
# https://github.com/sheerhealth/sheer/wiki/Production-Release-Process
#   v<YYYY>-<MM>-<DD>.<number of deploys that day>
# Release notes are always generated by GitHub from PR labels (.github/release.yml).

const REPO = "sheerhealth/sheer"

def fail [msg: string] {
  error make --unspanned {msg: $msg}
}

def gh-run [args: list<string>] {
  let result = (^gh ...$args | complete)

  if ($result.exit_code != 0) {
    let details = (
      [($result.stderr | default "" | str trim) ($result.stdout | default "" | str trim)]
      | where {|part| $part | is-not-empty }
      | str join "\n"
    )
    fail $"`gh ($args | str join ' ')` failed:\n($details)"
  }

  $result.stdout
}

def gh-json [args: list<string>] {
  gh-run $args | from json
}

# Copy text to the system clipboard, matching the `clip` helper in home/utils.nu.
def copy-to-clipboard [] {
  let text = $in

  if ($nu.os-info.name == "macos") {
    $text | ^pbcopy
  } else {
    $text | ^wl-copy
  }
}

# Every version number already claimed today, from both tags and releases
# (drafts included, since a draft holds a tag name without creating the ref).
def used-versions [today: string] {
  let tag_refs = (
    gh-json [api $"repos/($REPO)/git/matching-refs/tags/v($today)."]
    | get --optional ref
    | default []
    | each {|ref| $ref | str replace "refs/tags/" "" }
  )

  let release_tags = (
    gh-json [release list --repo $REPO --limit 50 --json tagName]
    | get --optional tagName
    | default []
  )

  $tag_refs
  | append $release_tags
  | uniq
  | parse $"v($today).{version}"
  | get version
  | where {|version| $version =~ '^[0-9]+$' }
  | each {|version| $version | into int }
}

def next-tag [] {
  let today = (date now | format date "%Y-%m-%d")
  let used = (used-versions $today)
  let version = if ($used | is-empty) { 0 } else { ($used | math max) + 1 }

  $"v($today).($version)"
}

# Resolve a commit-ish (sha, branch, tag) to the commit the release will target.
# The wiki asks for a specific commit rather than the moving `main` ref.
def resolve-commit [rev: string] {
  let commit = (gh-json [api $"repos/($REPO)/commits/($rev)"])

  {
    sha: $commit.sha
    subject: ($commit.commit.message | lines | first)
    author: ($commit.commit.author.name)
    committed: ($commit.commit.committer.date | into datetime)
  }
}

# Rollup of CI for the target commit, so a red build is obvious before drafting.
def check-state [sha: string] {
  let query = '
query($owner:String!, $repo:String!, $sha:GitObjectID!) {
  repository(owner:$owner, name:$repo) {
    object(oid:$sha) {
      ... on Commit {
        statusCheckRollup { state }
      }
    }
  }
}'

  let parts = ($REPO | split row "/")
  let response = (
    gh-json [
      api
      graphql
      -f
      $"query=($query)"
      -F
      $"owner=($parts | first)"
      -F
      $"repo=($parts | last)"
      -F
      $"sha=($sha)"
    ]
  )

  $response.data.repository.object.statusCheckRollup?.state? | default "NONE"
}

def colored-check-state [state: string] {
  let color = match $state {
    "SUCCESS" => (ansi green)
    "PENDING" => (ansi yellow)
    _ => (ansi red)
  }

  $"($color)($state)(ansi reset)"
}

def generate-notes [tag: string sha: string previous_tag: string] {
  let previous_args = if ($previous_tag | is-empty) {
    []
  } else {
    [-f $"previous_tag_name=($previous_tag)"]
  }

  gh-json [
    api
    --method
    POST
    $"repos/($REPO)/releases/generate-notes"
    -f
    $"tag_name=($tag)"
    -f
    $"target_commitish=($sha)"
    ...$previous_args
  ]
}

def confirm [question: string] {
  let answer = (input $"($question) (ansi cyan)[y/N](ansi reset) " | str trim | str lowercase)
  $answer in ["y" "yes"]
}

# Draft the next production release for sheerhealth/sheer.
def main [
  commit: string = "main" # commit, branch, or tag the release targets
  --tag: string # override the calculated CalVer tag
  --previous-tag: string # tag to diff against, when GitHub's auto choice is wrong
  --yes (-y) # skip the confirmation prompt
] {
  let target = (resolve-commit $commit)
  let tag = ($tag | default (next-tag))
  let notes = (generate-notes $tag $target.sha ($previous_tag | default ""))

  print (
    {
      repo: $REPO
      tag: $tag
      title: $notes.name
      target: ($target.sha | str substring 0..<12)
      commit: $target.subject
      author: $target.author
      committed: ($target.committed | format date "%Y-%m-%d %H:%M:%S")
      checks: (colored-check-state (check-state $target.sha))
      draft: true
      prerelease: false
    }
    | table --expand
  )

  print $"\n(ansi default_dimmed)--- release notes \(auto-generated by github\) ---(ansi reset)"
  print ($notes.body | str trim)
  print ""

  if (not $yes) and (not (confirm "create this draft release?")) {
    print -e "aborted"
    exit 1
  }

  let notes_file = (mktemp --tmpdir --suffix .md)
  $notes.body | save --force $notes_file

  let output = try {
    gh-run [
      release
      create
      $tag
      --repo
      $REPO
      --target
      $target.sha
      --title
      $notes.name
      --notes-file
      $notes_file
      --draft
    ]
  } catch {|err|
    rm --force $notes_file
    fail ($err.msg | default ($err | to json))
  }

  rm --force $notes_file

  let url = ($output | lines | where {|line| $line | str starts-with "http" } | last)
  $url | copy-to-clipboard

  print $"(ansi green)draft release ($tag) created(ansi reset) (ansi default_dimmed)\(link copied to clipboard\)(ansi reset)"
  print $url
}

# Print the CalVer tag the next release should use.
def "main tag" [] {
  next-tag
}
